// Re-export everything from validation-schemas.ts for backward compatibility
export {
  projectSchema,
  clientSchema,
  taskSchema,
  invoiceSchema,
  meetingSchema,
  contractSchema,
  employeeSchema,
  supplierSchema,
  siteVisitSchema,
  defectSchema,
  submittalSchema,
  changeOrderSchema,
  rfiSchema,
  getErrorMessage,
  errorMessages,
  type ProjectFormData,
  type ClientFormData,
  type TaskFormData,
  type InvoiceFormData,
  type MeetingFormData,
  type ContractFormData,
  type EmployeeFormData,
  type SupplierFormData,
  type SiteVisitFormData,
  type DefectFormData,
  type SubmittalFormData,
  type ChangeOrderFormData,
  type RfiFormData,
} from "./validation-schemas";
