#!/bin/bash

# ============================================
# BluePrint SaaS - Production Key Generator
# ============================================
# This script generates secure keys for production deployment
# Run this script before deploying to production
#
# Usage: ./scripts/generate-keys.sh > .env.production

echo "# ============================================"
echo "# BluePrint SaaS - Production Environment"
echo "# Generated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
echo "# ============================================"
echo ""
echo "# ============================================"
echo "# Application Settings"
echo "# ============================================"
echo "NODE_ENV=production"
echo "NEXT_PUBLIC_APP_URL=https://your-domain.com"
echo "NEXT_PUBLIC_APP_NAME=BluePrint SaaS"
echo ""
echo "# ============================================"
echo "# Database Configuration"
echo "# ============================================"
echo "# IMPORTANT: Change the database password below!"
echo "DATABASE_URL=postgresql://blueprint:CHANGE_ME@db:5432/blueprint"
echo ""
echo "# ============================================"
echo "# Authentication"
echo "# ============================================"
echo "# JWT Secret (generated securely)"
JWT_SECRET=$(openssl rand -base64 32)
echo "JWT_SECRET=$JWT_SECRET"
echo ""
echo "# ============================================"
echo "# Encryption Key for Sensitive Data"
echo "# ============================================"
echo "# Used for encrypting API keys, 2FA secrets, PII, etc."
ENCRYPTION_KEY=$(openssl rand -hex 32)
echo "ENCRYPTION_KEY=$ENCRYPTION_KEY"
echo ""
echo "# ============================================"
echo "# Redis Cache"
echo "# ============================================"
REDIS_PASSWORD=$(openssl rand -base64 24)
echo "REDIS_PASSWORD=$REDIS_PASSWORD"
echo ""
echo "# ============================================"
echo "# Rate Limiting"
echo "# ============================================"
echo "RATE_LIMIT_MAX=100"
echo "RATE_LIMIT_WINDOW_MS=60000"
echo "RATE_LIMIT_AUTH_MAX=10"
echo "RATE_LIMIT_AUTH_WINDOW_MS=60000"
echo ""
echo "# ============================================"
echo "# Optional Services (configure as needed)"
echo "# ============================================"
echo "# STRIPE_SECRET_KEY=sk_live_your_stripe_secret_key"
echo "# STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret"
echo "# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_live_your_publishable_key"
echo "# SMTP_HOST=smtp.gmail.com"
echo "# SMTP_PORT=587"
echo "# SMTP_USER=your_email@gmail.com"
echo "# SMTP_PASS=your_app_password_here"
echo "# EMAIL_FROM=noreply@yourdomain.com"
echo "# OPENAI_API_KEY=sk-your_openai_api_key"
echo "# SENTRY_DSN=https://your_sentry_dsn"
echo ""
echo "# ============================================"
echo "# Security Checklist:"
echo "# ============================================"
echo "# [ ] Change DATABASE_URL password"
echo "# [ ] Update NEXT_PUBLIC_APP_URL to your domain"
echo "# [ ] Configure Stripe keys (if using payments)"
echo "# [ ] Configure SMTP settings (if using email)"
echo "# [ ] Configure CORS_ORIGINS for your domains"
echo "# [ ] Review and remove unused variables"
echo ""
